name : documentation

on:
  push:
    branches: "main"
  pull_request:
    types: [ closed ]


permissions :
  contents: write

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - name: Select repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Generate javadoc
        run: mvn -B javadoc::javadoc
      - name: Publish website
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/reports/apidocs/